name: CI
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm first
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Now Node + pnpm cache works because pnpm exists
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
